# Site settings
site-title: Bits 2 Bedside – a physician commentary on healthcare UX in the Digital Age · Jake McClure .net
title: Bits 2 Bedside – a physician commentary on healthcare UX in the Digital Age · Jake McClure .net
blog-title: bits <span>2</span> Bedside
description: a physician commentary on healthcare UX in the Digital Age · Jake McClure .net
site-description: >
  Healthcare in the Mobile, Digital Age
blog-description: >
  A millennial physician's commentary on healthcare delivery and tech innovation intersecting with the systematic friction blocking its path.
logo: "/assets/images/JM-steth.svg"
exclude: [
  "node_modules",
  "LICENSE",
  "package.json",
  "README.md",
  "Gemfile",
  "gulpfile.babel.js", "gulpfile.js",
  ".babelrc",
  ".gitignore",
  "sass",
  "scss",
  "images", "preview.jpg",
  "css",
  "js",
  "fonts",
  ".DS_store"]
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://JakeMcClure.net" # the base hostname & protocol for your site
paginate:	4 # The number of posts to show per page on your homepage

name: 'Jake McClure'
bio: >
  a millennial physician who recognizes that patients are engaged in "social media" not the latest journal article
author:
  twitter: Jake_McClure
author_image: "/assets/images/author.png"
blog-header: "/assets/images/b2b-header.png"
twitter_username: Jake_McClure
twitter:
  username: Jake_McClure
github_username:  JakeMcClure
email:  DJakeMcClureMD+site@gmail.com
email_username:  DJakeMcClureMD+site@gmail.com
youtube_username:  UC6yHs_AREfWOMhR3Qixf2aA
linkedin_username:  mcclurejake
medium_username:  JakeMcClure
nuzzel_username:  Jake_McClure
snapchat_username: Jake-McClure


# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
  - jekyll-seo-tag

permalink:  pretty
show_drafts:  true
host:  localhost
port:  8080
