# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jake McClure .net
email: DJakeMcClureMD+site@gmail.com
description: >
  physician · clinical mind, UX eye
logo: "/assets/images/JM-bulb-border.svg"
exclude:  ["node_modules", "gulpfile.js", "package.json", "preview.jpg", ".DS_store"]
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://JakeMcClure.net" # the base hostname & protocol for your site
paginate:	4 # The number of posts to show per page on your homepage

name: 'Jake McClure'
bio: >
author_image: "/assets/images/author.png"
twitter_username: Jake_McClure
github_username:  JakeMcClure

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate

permalink:  pretty
show_drafts:  false
host:  localhost
port:  8080
