markdown:  kramdown
url:  "http://jakemcclure.net"
baseurl:  ""
exclude:  ["node_modules", "gulpfile.js", "package.json", "preview.jpg"]
Collections:
  infographics:
    Output:  true
  reviews:
    Output:  true
  tutorials:
    Output:  true
title:  Jake McClure .net
description:  one physician's perspective on our leverage of technology in healthcare

permalink:  pretty
show_drafts:  false

email:  DJakeMcClureMD+site@gmail.com
email_username:  DJakeMcClureMD+site@gmail.com
twitter_username:  Jake_McClure
github_username:  JakeMcClure
instagram_username:  _JakeMcClure
youtube_username:  UC6yHs_AREfWOMhR3Qixf2aA
linkedin_username:  mcclurejake
medium_username:  JakeMcClure
nuzzel_username:  Jake_McClure


# destination:  _deploy

host:  localhost
port:  8080
incremental:  false
# Build settings
# ?need custom md processor (https://jekyllrb.com/docs/configuration/#custom-markdown-processors)

  #redcarpet:
    #extensions:  ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
