name: Your New Jekyll Site
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
highlighter: null #or pygments #or null #or rouge
exclude: ["node_modules",
  "gulpfile.js",
  "package.json",
  "preview.jpg",
  "README.md"]

